#!/bin/bash

# ================================================================================================
# FIX IAM PERMISSIONS FOR PRODUCTION DEPLOYMENT
# ================================================================================================
# This script helps diagnose and provides commands to fix IAM permission issues
# ================================================================================================

echo "🔍 Checking IAM Permissions..."
echo "=================================================="
echo ""

AWS_PROFILE="ingenet3d"

# Get current user identity
echo "Current IAM User:"
aws sts get-caller-identity --profile $AWS_PROFILE --output json

echo ""
echo "=================================================="
echo "⚠️  ACCESS DENIED ERROR DETECTED"
echo "=================================================="
echo ""
echo "The IAM user 'Ingenet' needs these permissions:"
echo ""
echo "Required S3 Permissions:"
echo "  - s3:PutBucketPolicy"
echo "  - s3:PutBucketPublicAccessBlock"
echo "  - s3:PutBucketWebsite"
echo "  - s3:CreateBucket"
echo "  - s3:ListBucket"
echo "  - s3:PutObject"
echo "  - s3:GetObject"
echo "  - s3:DeleteObject"
echo ""
echo "Required CloudFront Permissions:"
echo "  - cloudfront:CreateDistribution"
echo "  - cloudfront:CreateInvalidation"
echo "  - cloudfront:GetDistribution"
echo "  - cloudfront:ListInvalidations"
echo ""
echo "=================================================="
echo "SOLUTION OPTIONS:"
echo "=================================================="
echo ""
echo "Option 1: Add Permissions via AWS Console (RECOMMENDED)"
echo "--------------------------------------------------------"
echo "1. Go to: https://console.aws.amazon.com/iam/"
echo "2. Click 'Users' → Select 'Ingenet' user"
echo "3. Click 'Add permissions' → 'Attach policies directly'"
echo "4. Add these managed policies:"
echo "   - AmazonS3FullAccess"
echo "   - CloudFrontFullAccess"
echo "5. Click 'Next' → 'Add permissions'"
echo ""
echo "Option 2: Use AWS CLI (If you have admin access)"
echo "--------------------------------------------------------"
echo "Run these commands:"
echo ""
echo "# Attach S3 Full Access"
echo "aws iam attach-user-policy \\"
echo "  --user-name Ingenet \\"
echo "  --policy-arn arn:aws:iam::aws:policy/AmazonS3FullAccess"
echo ""
echo "# Attach CloudFront Full Access"
echo "aws iam attach-user-policy \\"
echo "  --user-name Ingenet \\"
echo "  --policy-arn arn:aws:iam::aws:policy/CloudFrontFullAccess"
echo ""
echo "=================================================="
echo "ALTERNATIVE: Simplified Setup (Without Bucket Policy)"
echo "=================================================="
echo ""
echo "If you can't modify IAM permissions, we can use a"
echo "simplified setup that works with current permissions."
echo ""
echo "This uses CloudFront Origin Access Identity instead"
echo "of public bucket policy."
echo ""
echo "Would you like to use the simplified setup?"
echo "If yes, run: ./setup-production-infrastructure-simple.sh"
echo ""
